services:
  rplay_server:
    container_name: rplay_server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.rplay_server.rule=Host(`rplay-api.haniking.com`)
      - traefik.http.routers.rplay_server.entrypoints=websecure
      - traefik.http.routers.rplay_server.tls.certresolver=myresolver
    networks:
      - web
  rtmp_server:
    container_name: rtmp_server
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: DockerfileRtmp
    volumes:
      - /usr/local/bin/ffmpeg:/usr/local/bin/ffmpeg
      - /media:app/media
    expose:
      - 1935 # RTMP
      - 8000 # dashboard
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true
